<?php
//前台会员管理控制器
class UserController extends PlatformController
{
    //显示会员注册表单动作
    public function registerAction()
    {
        //和indexController中的代码一样
        //调用MasterModel获取站长信息
        $master=Factory::M('MasterModel');
        $masterInfo=$master->getMasterInfo();
        //分配变量
        $this->assign('masterInfo',$masterInfo);
        //调用Article模型
        $article=Factory::M('ArticleModel');
        //获取最新文章列表
        $newArt=$article->getNewArt(8);
        //分配变量
        $this->assign('newArt',$newArt);
        //获取最热推荐文章列表
        $rmdArtByHits=$article->getRmdArtByHits(8);
        //分配变量
        $this->assign('rmdArtByHits',$rmdArtByHits);
        //显示输出视图文件
        $this->display('register.html');
    }
    //处理会员注册动作
    public function dealRegisterAction()
    {
        //接收数据
        $userInfo=array();
        $user_name=$_POST['user_name'];
        //判断用户名是否为空
        if(empty($user_name))
        {
            $this->jump('index.php?p=Home&c=User&a=register',':(用户名不能为空!');
        }
        //判断用户名是否超出长度
        if(strlen($user_name)>20)
        {
            $this->jump('index.php?p=Home&c=User&a=register',':(用户名超出范围!');
        }
        //判断用户名是否一已经存在
        //调用模型
        $user=Factory::M('UserModel');
        if($user->if_name_exists($user_name))
        {
            //用户已经存在
            $this->jump('index.php?p=Home&c=User&a=register',':(用户名已经存在!');
        }
        $userInfo['user_name']=$user_name;
        //判断密码是否一致
        $user_pass1=trim($_POST['pass1']);
        $user_pass2=trim($_POST['pass2']);
        if(empty($user_pass1) || empty($user_pass2))
        {
            $this->jump('index.php?p=Home&c=User&a=register',':(密码不能为空!');
        }
        if($user_pass1!==$user_pass2)
        {
            $this->jump('index.php?p=Home&c=User&a=register',':(两次密码不一致!');
        }
        $userInfo['user_pass']=md5($user_pass1);
        //判断是否上传了头像
        if($_FILES['user_image']['error']!=4)
        {
            $upload=Factory::M('Upload');
            $allow=array('image/png','image/jpeg','image/gif','image/jpg');
            $path=UPLOADS_DIR.'user';
            //调用uploadAction
            if($result=$upload->uploadAction($_FILES['user_image'],$allow,$path))
            {
                $userInfo['user_image']=$result;
            }else{
                //上传失败，记录错误并跳转
                $this->jump('index.php?p=Home&c=User&a=register',Upload::$error);
            }
        }else{
            $userInfo['user_image']='default.jpg';
        }
        $userInfo['user_time']=time();
        //调用模型，数据入库
        $result=$user->insertUser($userInfo);
        if($result)
        {
            $this->jump('index.php?p=Home&c=User&a=login',':)注册成功!');
        }else{
            $this->jump('index.php?p=Home&c=User&a=register',':(发生未知错误，注册失败!');
        }
    }
    //显示会员登录表单动作
    public function loginAction()
    {
        //和indexController中的代码一样
        //调用MasterModel获取站长信息
        $master=Factory::M('MasterModel');
        $masterInfo=$master->getMasterInfo();
        //分配变量
        $this->assign('masterInfo',$masterInfo);
        //调用Article模型
        $article=Factory::M('ArticleModel');
        //获取最新文章列表
        $newArt=$article->getNewArt(8);
        //分配变量
        $this->assign('newArt',$newArt);
        //获取最热推荐文章列表
        $rmdArtByHits=$article->getRmdArtByHits(8);
        //分配变量
        $this->assign('rmdArtByHits',$rmdArtByHits);
        //显示输出视图文件
        $this->display('login.html');
    }
    //处理会员登录动作
    public function dealLoginAction()
    {
        //接收数据
        $user_name=$_POST['user_name'];
        $user_pass=trim($_POST['pass1']);
        if(empty($user_name) || empty($user_pass))
        {
            $this->jump('index.php?p=Home&c=User&a=login',':(用户名和密码都不能为空!');
        }
        //判断用户名和密码是否合法
        $user=Factory::M('UserModel');
        $result=$user->check($user_name,md5($user_pass));
        if($result)
        {
            //将用户信息存储到session中
            @session_start();
            $_SESSION['user_info']=$result;   //数组信息
            $this->jump('index.php?p=Home&c=User&a=index');
        }else{
            $this->jump('index.php?p=Home&c=User&a=login',':(用户名或密码错误!');
        }
    }
    //logout用户退出动作
    public function logoutAction()
    {
        unset($_SESSION['user_info']);
        session_destroy();
        $this->jump('index.php?p=Home&c=User&a=index');
    }
    //需要增加的动作：登录后、退出登录 回到首页动作
    public function IndexAction()
    {
        $article=Factory::M('ArticleModel');
        //获取推荐文章信息
        $recommendArt=$article->getRecommendArt(5);
        //分配变量
        $this->assign('recommendArt',$recommendArt);
        //调用MasterModel获取站长信息
        $master=Factory::M('MasterModel');
        $masterInfo=$master->getMasterInfo();
        //分配变量
        $this->assign('masterInfo',$masterInfo);
        //获取最新文章列表
        $newArt=$article->getNewArt(8);
        //分配变量
        $this->assign('newArt',$newArt);
        //获取最热推荐文章列表
        $rmdArtByHits=$article->getRmdArtByHits(8);
        //分配变量
        $this->assign('rmdArtByHits',$rmdArtByHits);
        //显示输出视图文件
        $this->display('index.html');
    }
}